### PR TITLE
Add support for obtaining user access token.

### PR DESCRIPTION
**Pull request by johnou**
See https://github.com/revetkn/restfb/issues/93

### CODE REVIEW

**Comment by nbartels** [comment]
put the commit in dev via cherry-pick (5df277bce4a1350ab2a452396d424f6ec509e58a)

**Comment by johnou** [comment]
Thanks!

**Comment by johnou** [comment]
Kind reminder that I put 1.7.x in the javadoc as I was unsure what release the PR would hit.

**Comment by nbartels** [comment]
Yes, thanks. I noticed that. I'll change it to 1.8.0 as soon as I prepare the release.

**Pull request closed without merging**
