### PR TITLE
Added executeDelete

### PR DESCRIPTION
**Pull request by erichydrick**
Added executeDelete() to WebRequestor, and implementations in ClasspathWebRequestor, DefaultWebRequestor, and FakeWebRequestor.

### CODE REVIEW

**Comment by nbartels** [comment]
Thx for your pull request. But I don't understand why you need the change and what's the intention. Because restfb provides the ```FacebookClient.deleteObject``` method. It uses the "http method override" facebook provides. So is there an problem with the current implementation?

Have a look here: https://developers.facebook.com/docs/graph-api/using-graph-api/v2.2#deleting

**Comment by erichydrick** [comment]
I've been working with custom audiences, and removing members uses an HTTP
DELETE. Method override would probably work, but since a Java library could
support HTTP DELETEs, I thought it would be more intuitive to have an
executeDelete rather than asking them to issue a post request with
method=delete in the parameter string.

**Comment by nbartels** [comment]
Okay. I cherry-picked your commit and work a bit on it. Both ways are supported and you can activate the fallback mechanism with a simple flag.

**Comment by erichydrick** [comment]
Thanks!

Eric

**Comment by nbartels** [comment]
commit added to Issue #173  - close the pull request

**Pull request closed without merging**
